version: '3'

services:
  lb:
   image: traefik:latest
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - traefik-config:/etc/traefik/acme
   ports:
     - "80:80"
     - "443:443"
   deploy:
     placement:
       constraints:
         - node.role == manager
   command: >
     --web
     --docker
     --docker.swarmmode
     --docker.domain=${DOMAIN}
     --docker.watch
     --entryPoints='Name:http Address::80 Redirect.EntryPoint:https'
     --entryPoints='Name:https Address::443 TLS'
     --defaultEntryPoints=http,https
     --acme.entryPoint=https
     --acme.email=${EMAIL}
     --acme.storage=/etc/traefik/acme/acme.json
     --acme.domains=domain.tld
     --acme.onHostRule=true
     --acme.httpChallenge.entryPoint=http
     --accesslogsfile=/dev/stdout
     --logLevel=INFO
  lightwalletd:
    build: .Dockerfiles/lightwalletd
    image: zcash-hackworks/lightwalletd:latest
    volumes:
      - testnet-chain:/home/zcash/.zcash
      - testnet-params:/home/zcash/.zcash-params
    deploy:
      labels:
        - traefik.frontend.rule=Host:lightwalletd.${DOMAIN}
        - traefik.port=9067
        - traefik.weight=7
        - traefik.frontend.entryPoints=https
volumes:
   testnet-chain:
   testnet-params:
   traefik-config:
